title: Juan Trinidad # your name (or website title) here
logo: "/images/IMG_8372 2.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm Juan, a Software Developer Student based in New Jersey 
  <br><br>
  I enjoy creating web application using JavaScript,React,Redux, and Node.JS.
  <br><br>
  <a href="https://www.linkedin.com/in/juan-trinidad">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
